#!/bin/bash

rmthis=`ls`
echo ${rmthis}

docker run -v `pwd`:/data cyverseuk/gwasser:26.07.2016 ${gFile} ${pFile} ${mFile} ${PHENOS} ${COVS} --outDir output ${mkplots} ${saveinter};
#######previous tag needs to be update as soon as we download the other image


rmthis=`echo ${rmthis} | sed s/.*\.out// -`
rmthis=`echo ${rmthis} | sed s/.*\.err// -`
rm --verbose ${rmthis}
